cache:
  file_cache:
      path: tofawiki/cache/data/file_cache.json
  redis_cache:
      port: 6379
      host: '127.0.0.1'

wsgi:
  host: localhost:8080
  application_root: ""
  url_prefix: ""

enwiki:
  code_lang: 'en'
